package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * AlertTypeDic generated by hbm2java
 */
public class AlertTypeDic implements java.io.Serializable {

	private int alertTypeId;
	private String alertTypeName;
	private String description;
	private String imagePath;
	private String voicePath;
	private Set<Rules> ruleses = new HashSet<Rules>(0);
	private Set<AlertHistory> alertHistories = new HashSet<AlertHistory>(0);
	private Set<PrivateRules> privateRuleses = new HashSet<PrivateRules>(0);

	public AlertTypeDic() {
	}

	public AlertTypeDic(int alertTypeId) {
		this.alertTypeId = alertTypeId;
	}

	public AlertTypeDic(int alertTypeId, String alertTypeName,
			String description, String imagePath, String voicePath,
			Set<Rules> ruleses, Set<AlertHistory> alertHistories,
			Set<PrivateRules> privateRuleses) {
		this.alertTypeId = alertTypeId;
		this.alertTypeName = alertTypeName;
		this.description = description;
		this.imagePath = imagePath;
		this.voicePath = voicePath;
		this.ruleses = ruleses;
		this.alertHistories = alertHistories;
		this.privateRuleses = privateRuleses;
	}

	public int getAlertTypeId() {
		return this.alertTypeId;
	}

	public void setAlertTypeId(int alertTypeId) {
		this.alertTypeId = alertTypeId;
	}

	public String getAlertTypeName() {
		return this.alertTypeName;
	}

	public void setAlertTypeName(String alertTypeName) {
		this.alertTypeName = alertTypeName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public String getVoicePath() {
		return this.voicePath;
	}

	public void setVoicePath(String voicePath) {
		this.voicePath = voicePath;
	}

	public Set<Rules> getRuleses() {
		return this.ruleses;
	}

	public void setRuleses(Set<Rules> ruleses) {
		this.ruleses = ruleses;
	}

	public Set<AlertHistory> getAlertHistories() {
		return this.alertHistories;
	}

	public void setAlertHistories(Set<AlertHistory> alertHistories) {
		this.alertHistories = alertHistories;
	}

	public Set<PrivateRules> getPrivateRuleses() {
		return this.privateRuleses;
	}

	public void setPrivateRuleses(Set<PrivateRules> privateRuleses) {
		this.privateRuleses = privateRuleses;
	}

}
