package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver implements java.io.Serializable {

	private int driverId;
	private Users users;
	private String name;
	private Short drivingLicenceType;
	private String tel;
	private Short annualCheckState;
	private String certificateNumber;
	private Date certificateDue;
	private String dangerousCertLevel;
	private Date dangerousCertDue;
	private Short driverState;
	private Set<TaskDriver> taskDrivers = new HashSet<TaskDriver>(0);

	public Driver() {
	}

	public Driver(int driverId, String name) {
		this.driverId = driverId;
		this.name = name;
	}

	public Driver(int driverId, Users users, String name,
			Short drivingLicenceType, String tel, Short annualCheckState,
			String certificateNumber, Date certificateDue,
			String dangerousCertLevel, Date dangerousCertDue,
			Short driverState, Set<TaskDriver> taskDrivers) {
		this.driverId = driverId;
		this.users = users;
		this.name = name;
		this.drivingLicenceType = drivingLicenceType;
		this.tel = tel;
		this.annualCheckState = annualCheckState;
		this.certificateNumber = certificateNumber;
		this.certificateDue = certificateDue;
		this.dangerousCertLevel = dangerousCertLevel;
		this.dangerousCertDue = dangerousCertDue;
		this.driverState = driverState;
		this.taskDrivers = taskDrivers;
	}

	public int getDriverId() {
		return this.driverId;
	}

	public void setDriverId(int driverId) {
		this.driverId = driverId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Short getDrivingLicenceType() {
		return this.drivingLicenceType;
	}

	public void setDrivingLicenceType(Short drivingLicenceType) {
		this.drivingLicenceType = drivingLicenceType;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Short getAnnualCheckState() {
		return this.annualCheckState;
	}

	public void setAnnualCheckState(Short annualCheckState) {
		this.annualCheckState = annualCheckState;
	}

	public String getCertificateNumber() {
		return this.certificateNumber;
	}

	public void setCertificateNumber(String certificateNumber) {
		this.certificateNumber = certificateNumber;
	}

	public Date getCertificateDue() {
		return this.certificateDue;
	}

	public void setCertificateDue(Date certificateDue) {
		this.certificateDue = certificateDue;
	}

	public String getDangerousCertLevel() {
		return this.dangerousCertLevel;
	}

	public void setDangerousCertLevel(String dangerousCertLevel) {
		this.dangerousCertLevel = dangerousCertLevel;
	}

	public Date getDangerousCertDue() {
		return this.dangerousCertDue;
	}

	public void setDangerousCertDue(Date dangerousCertDue) {
		this.dangerousCertDue = dangerousCertDue;
	}

	public Short getDriverState() {
		return this.driverState;
	}

	public void setDriverState(Short driverState) {
		this.driverState = driverState;
	}

	public Set<TaskDriver> getTaskDrivers() {
		return this.taskDrivers;
	}

	public void setTaskDrivers(Set<TaskDriver> taskDrivers) {
		this.taskDrivers = taskDrivers;
	}

}
