package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * FMaterialKeepLog generated by hbm2java
 */
public class FMaterialKeepLog implements java.io.Serializable {

	private long id;
	private FVehicleMaterial FVehicleMaterial;
	private String keeper;
	private Date occurDate;
	private String comment;
	private String operator;

	public FMaterialKeepLog() {
	}

	public FMaterialKeepLog(long id) {
		this.id = id;
	}

	public FMaterialKeepLog(long id, FVehicleMaterial FVehicleMaterial,
			String keeper, Date occurDate, String comment, String operator) {
		this.id = id;
		this.FVehicleMaterial = FVehicleMaterial;
		this.keeper = keeper;
		this.occurDate = occurDate;
		this.comment = comment;
		this.operator = operator;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public FVehicleMaterial getFVehicleMaterial() {
		return this.FVehicleMaterial;
	}

	public void setFVehicleMaterial(FVehicleMaterial FVehicleMaterial) {
		this.FVehicleMaterial = FVehicleMaterial;
	}

	public String getKeeper() {
		return this.keeper;
	}

	public void setKeeper(String keeper) {
		this.keeper = keeper;
	}

	public Date getOccurDate() {
		return this.occurDate;
	}

	public void setOccurDate(Date occurDate) {
		this.occurDate = occurDate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

}
