package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * FMaterialKeepLog generated by hbm2java
 */
public class FMaterialKeepLog implements java.io.Serializable {

	private long id;
	private Users users;
	private FVehicleMaterial FVehicleMaterial;
	private String keeper;
	private Date occurDate;
	private String comment;

	public FMaterialKeepLog() {
	}

	public FMaterialKeepLog(long id) {
		this.id = id;
	}

	public FMaterialKeepLog(long id, Users users,
			FVehicleMaterial FVehicleMaterial, String keeper, Date occurDate,
			String comment) {
		this.id = id;
		this.users = users;
		this.FVehicleMaterial = FVehicleMaterial;
		this.keeper = keeper;
		this.occurDate = occurDate;
		this.comment = comment;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public FVehicleMaterial getFVehicleMaterial() {
		return this.FVehicleMaterial;
	}

	public void setFVehicleMaterial(FVehicleMaterial FVehicleMaterial) {
		this.FVehicleMaterial = FVehicleMaterial;
	}

	public String getKeeper() {
		return this.keeper;
	}

	public void setKeeper(String keeper) {
		this.keeper = keeper;
	}

	public Date getOccurDate() {
		return this.occurDate;
	}

	public void setOccurDate(Date occurDate) {
		this.occurDate = occurDate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
