package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FMaterialKeepLog generated by hbm2java
 */
public class FMaterialKeepLog implements java.io.Serializable {

	private FMaterialKeepLogId id;
	private Users users;
	private FVehicleMaterial FVehicleMaterial;

	public FMaterialKeepLog() {
	}

	public FMaterialKeepLog(FMaterialKeepLogId id) {
		this.id = id;
	}

	public FMaterialKeepLog(FMaterialKeepLogId id, Users users,
			FVehicleMaterial FVehicleMaterial) {
		this.id = id;
		this.users = users;
		this.FVehicleMaterial = FVehicleMaterial;
	}

	public FMaterialKeepLogId getId() {
		return this.id;
	}

	public void setId(FMaterialKeepLogId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public FVehicleMaterial getFVehicleMaterial() {
		return this.FVehicleMaterial;
	}

	public void setFVehicleMaterial(FVehicleMaterial FVehicleMaterial) {
		this.FVehicleMaterial = FVehicleMaterial;
	}

}
