package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * SegmentRules generated by hbm2java
 */
public class SegmentRules implements java.io.Serializable {

	private long segRuleId;
	private Rules rules;
	private PrivateRules privateRules;
	private TaskSegment taskSegment;
	private Short stateTag;

	public SegmentRules() {
	}

	public SegmentRules(long segRuleId) {
		this.segRuleId = segRuleId;
	}

	public SegmentRules(long segRuleId, Rules rules, PrivateRules privateRules,
			TaskSegment taskSegment, Short stateTag) {
		this.segRuleId = segRuleId;
		this.rules = rules;
		this.privateRules = privateRules;
		this.taskSegment = taskSegment;
		this.stateTag = stateTag;
	}

	public long getSegRuleId() {
		return this.segRuleId;
	}

	public void setSegRuleId(long segRuleId) {
		this.segRuleId = segRuleId;
	}

	public Rules getRules() {
		return this.rules;
	}

	public void setRules(Rules rules) {
		this.rules = rules;
	}

	public PrivateRules getPrivateRules() {
		return this.privateRules;
	}

	public void setPrivateRules(PrivateRules privateRules) {
		this.privateRules = privateRules;
	}

	public TaskSegment getTaskSegment() {
		return this.taskSegment;
	}

	public void setTaskSegment(TaskSegment taskSegment) {
		this.taskSegment = taskSegment;
	}

	public Short getStateTag() {
		return this.stateTag;
	}

	public void setStateTag(Short stateTag) {
		this.stateTag = stateTag;
	}

}
