package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

/**
 * SegmentDetail generated by hbm2java
 */
public class SegmentDetail implements java.io.Serializable {

	private long segDetailId;
	private Segment segment;
	private Double longValue;
	private Double latValue;
	private Byte tag;

	public SegmentDetail() {
	}

	public SegmentDetail(long segDetailId, Segment segment) {
		this.segDetailId = segDetailId;
		this.segment = segment;
	}

	public SegmentDetail(long segDetailId, Segment segment, Double longValue,
			Double latValue, Byte tag) {
		this.segDetailId = segDetailId;
		this.segment = segment;
		this.longValue = longValue;
		this.latValue = latValue;
		this.tag = tag;
	}

	public long getSegDetailId() {
		return this.segDetailId;
	}

	public void setSegDetailId(long segDetailId) {
		this.segDetailId = segDetailId;
	}

	public Segment getSegment() {
		return this.segment;
	}

	public void setSegment(Segment segment) {
		this.segment = segment;
	}

	public Double getLongValue() {
		return this.longValue;
	}

	public void setLongValue(Double longValue) {
		this.longValue = longValue;
	}

	public Double getLatValue() {
		return this.latValue;
	}

	public void setLatValue(Double latValue) {
		this.latValue = latValue;
	}

	public Byte getTag() {
		return this.tag;
	}

	public void setTag(Byte tag) {
		this.tag = tag;
	}

}
