package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * SystemSettings generated by hbm2java
 */
public class SystemSettings implements java.io.Serializable {

	private int settingId;
	private String name;
	private String description;
	private Double value;

	public SystemSettings() {
	}

	public SystemSettings(int settingId) {
		this.settingId = settingId;
	}

	public SystemSettings(int settingId, String name, String description,
			Double value) {
		this.settingId = settingId;
		this.name = name;
		this.description = description;
		this.value = value;
	}

	public int getSettingId() {
		return this.settingId;
	}

	public void setSettingId(int settingId) {
		this.settingId = settingId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

}
