package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * TaskRule generated by hbm2java
 */
public class TaskRule implements java.io.Serializable {

	private int id;
	private Task task;
	private Rules rules;

	public TaskRule() {
	}

	public TaskRule(int id, Task task, Rules rules) {
		this.id = id;
		this.task = task;
		this.rules = rules;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Rules getRules() {
		return this.rules;
	}

	public void setRules(Rules rules) {
		this.rules = rules;
	}

}
