package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * TaskEscorter generated by hbm2java
 */
public class TaskEscorter implements java.io.Serializable {

	private int id;
	private Task task;
	private Escorter escorter;

	public TaskEscorter() {
	}

	public TaskEscorter(int id) {
		this.id = id;
	}

	public TaskEscorter(int id, Task task, Escorter escorter) {
		this.id = id;
		this.task = task;
		this.escorter = escorter;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Escorter getEscorter() {
		return this.escorter;
	}

	public void setEscorter(Escorter escorter) {
		this.escorter = escorter;
	}

}
