package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TaskSegment generated by hbm2java
 */
public class TaskSegment implements java.io.Serializable {

	private int taskSegId;
	private Task task;
	private Segment segment;
	private Integer orderNo;
	private Double speedLimit;
	private Set<SegmentRules> segmentRuleses = new HashSet<SegmentRules>(0);

	public TaskSegment() {
	}

	public TaskSegment(int taskSegId, Task task, Segment segment) {
		this.taskSegId = taskSegId;
		this.task = task;
		this.segment = segment;
	}

	public TaskSegment(int taskSegId, Task task, Segment segment,
			Integer orderNo, Double speedLimit, Set<SegmentRules> segmentRuleses) {
		this.taskSegId = taskSegId;
		this.task = task;
		this.segment = segment;
		this.orderNo = orderNo;
		this.speedLimit = speedLimit;
		this.segmentRuleses = segmentRuleses;
	}

	public int getTaskSegId() {
		return this.taskSegId;
	}

	public void setTaskSegId(int taskSegId) {
		this.taskSegId = taskSegId;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Segment getSegment() {
		return this.segment;
	}

	public void setSegment(Segment segment) {
		this.segment = segment;
	}

	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	public Double getSpeedLimit() {
		return this.speedLimit;
	}

	public void setSpeedLimit(Double speedLimit) {
		this.speedLimit = speedLimit;
	}

	public Set<SegmentRules> getSegmentRuleses() {
		return this.segmentRuleses;
	}

	public void setSegmentRuleses(Set<SegmentRules> segmentRuleses) {
		this.segmentRuleses = segmentRuleses;
	}

}
