package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * TenMinTrack generated by hbm2java
 */
public class TenMinTrack implements java.io.Serializable {

	private long id;
	private Integer vehicleId;
	private Date recieveTime;
	private Double latValue;
	private Double longValue;
	private Short tag;
	private Double speed;
	private Short direction;

	public TenMinTrack() {
	}

	public TenMinTrack(long id) {
		this.id = id;
	}

	public TenMinTrack(long id, Integer vehicleId, Date recieveTime,
			Double latValue, Double longValue, Short tag, Double speed,
			Short direction) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.recieveTime = recieveTime;
		this.latValue = latValue;
		this.longValue = longValue;
		this.tag = tag;
		this.speed = speed;
		this.direction = direction;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	public Date getRecieveTime() {
		return this.recieveTime;
	}

	public void setRecieveTime(Date recieveTime) {
		this.recieveTime = recieveTime;
	}

	public Double getLatValue() {
		return this.latValue;
	}

	public void setLatValue(Double latValue) {
		this.latValue = latValue;
	}

	public Double getLongValue() {
		return this.longValue;
	}

	public void setLongValue(Double longValue) {
		this.longValue = longValue;
	}

	public Short getTag() {
		return this.tag;
	}

	public void setTag(Short tag) {
		this.tag = tag;
	}

	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	public Short getDirection() {
		return this.direction;
	}

	public void setDirection(Short direction) {
		this.direction = direction;
	}

}
