package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * VehicleTypeDic generated by hbm2java
 */
public class VehicleTypeDic implements java.io.Serializable {

	private short vehicleTypeId;
	private String vehicleTypeName;
	private String description;
	private Short stateTag;
	private Integer speedLimitation;
	private Set<Vehicle> vehicles = new HashSet<Vehicle>(0);

	public VehicleTypeDic() {
	}

	public VehicleTypeDic(short vehicleTypeId) {
		this.vehicleTypeId = vehicleTypeId;
	}

	public VehicleTypeDic(short vehicleTypeId, String vehicleTypeName,
			String description, Short stateTag, Integer speedLimitation,
			Set<Vehicle> vehicles) {
		this.vehicleTypeId = vehicleTypeId;
		this.vehicleTypeName = vehicleTypeName;
		this.description = description;
		this.stateTag = stateTag;
		this.speedLimitation = speedLimitation;
		this.vehicles = vehicles;
	}

	public short getVehicleTypeId() {
		return this.vehicleTypeId;
	}

	public void setVehicleTypeId(short vehicleTypeId) {
		this.vehicleTypeId = vehicleTypeId;
	}

	public String getVehicleTypeName() {
		return this.vehicleTypeName;
	}

	public void setVehicleTypeName(String vehicleTypeName) {
		this.vehicleTypeName = vehicleTypeName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Short getStateTag() {
		return this.stateTag;
	}

	public void setStateTag(Short stateTag) {
		this.stateTag = stateTag;
	}

	public Integer getSpeedLimitation() {
		return this.speedLimitation;
	}

	public void setSpeedLimitation(Integer speedLimitation) {
		this.speedLimitation = speedLimitation;
	}

	public Set<Vehicle> getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set<Vehicle> vehicles) {
		this.vehicles = vehicles;
	}

}
