package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * AlertHistory generated by hbm2java
 */
public class AlertHistory implements java.io.Serializable {

	private long alertId;
	private Vehicle vehicle;
	private AlertTypeDic alertTypeDic;
	private Short tag;
	private Date occurDate;
	private Date acctime;
	private Integer accUser;
	private String description;
	private String accComment;

	public AlertHistory() {
	}

	public AlertHistory(long alertId) {
		this.alertId = alertId;
	}

	public AlertHistory(long alertId, Vehicle vehicle,
			AlertTypeDic alertTypeDic, Short tag, Date occurDate, Date acctime,
			Integer accUser, String description, String accComment) {
		this.alertId = alertId;
		this.vehicle = vehicle;
		this.alertTypeDic = alertTypeDic;
		this.tag = tag;
		this.occurDate = occurDate;
		this.acctime = acctime;
		this.accUser = accUser;
		this.description = description;
		this.accComment = accComment;
	}

	public long getAlertId() {
		return this.alertId;
	}

	public void setAlertId(long alertId) {
		this.alertId = alertId;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public AlertTypeDic getAlertTypeDic() {
		return this.alertTypeDic;
	}

	public void setAlertTypeDic(AlertTypeDic alertTypeDic) {
		this.alertTypeDic = alertTypeDic;
	}

	public Short getTag() {
		return this.tag;
	}

	public void setTag(Short tag) {
		this.tag = tag;
	}

	public Date getOccurDate() {
		return this.occurDate;
	}

	public void setOccurDate(Date occurDate) {
		this.occurDate = occurDate;
	}

	public Date getAcctime() {
		return this.acctime;
	}

	public void setAcctime(Date acctime) {
		this.acctime = acctime;
	}

	public Integer getAccUser() {
		return this.accUser;
	}

	public void setAccUser(Integer accUser) {
		this.accUser = accUser;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAccComment() {
		return this.accComment;
	}

	public void setAccComment(String accComment) {
		this.accComment = accComment;
	}

}
