package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * CheckPoints generated by hbm2java
 */
public class CheckPoints implements java.io.Serializable {

	private long id;
	private Task task;
	private Region region;
	private Short checkedState;
	private Date enterDate;
	private Date leaveDate;
	private Short requiredCheckType;

	public CheckPoints() {
	}

	public CheckPoints(long id) {
		this.id = id;
	}

	public CheckPoints(long id, Task task, Region region, Short checkedState,
			Date enterDate, Date leaveDate, Short requiredCheckType) {
		this.id = id;
		this.task = task;
		this.region = region;
		this.checkedState = checkedState;
		this.enterDate = enterDate;
		this.leaveDate = leaveDate;
		this.requiredCheckType = requiredCheckType;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	public Short getCheckedState() {
		return this.checkedState;
	}

	public void setCheckedState(Short checkedState) {
		this.checkedState = checkedState;
	}

	public Date getEnterDate() {
		return this.enterDate;
	}

	public void setEnterDate(Date enterDate) {
		this.enterDate = enterDate;
	}

	public Date getLeaveDate() {
		return this.leaveDate;
	}

	public void setLeaveDate(Date leaveDate) {
		this.leaveDate = leaveDate;
	}

	public Short getRequiredCheckType() {
		return this.requiredCheckType;
	}

	public void setRequiredCheckType(Short requiredCheckType) {
		this.requiredCheckType = requiredCheckType;
	}

}
