package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Escorter generated by hbm2java
 */
public class Escorter implements java.io.Serializable {

	private int escorterId;
	private Users users;
	private String tel;
	private String name;
	private String certificateNumber;
	private Date certificateDue;
	private Short escorterState;
	private Set<TaskEscorter> taskEscorters = new HashSet<TaskEscorter>(0);

	public Escorter() {
	}

	public Escorter(int escorterId) {
		this.escorterId = escorterId;
	}

	public Escorter(int escorterId, Users users, String tel, String name,
			String certificateNumber, Date certificateDue, Short escorterState,
			Set<TaskEscorter> taskEscorters) {
		this.escorterId = escorterId;
		this.users = users;
		this.tel = tel;
		this.name = name;
		this.certificateNumber = certificateNumber;
		this.certificateDue = certificateDue;
		this.escorterState = escorterState;
		this.taskEscorters = taskEscorters;
	}

	public int getEscorterId() {
		return this.escorterId;
	}

	public void setEscorterId(int escorterId) {
		this.escorterId = escorterId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCertificateNumber() {
		return this.certificateNumber;
	}

	public void setCertificateNumber(String certificateNumber) {
		this.certificateNumber = certificateNumber;
	}

	public Date getCertificateDue() {
		return this.certificateDue;
	}

	public void setCertificateDue(Date certificateDue) {
		this.certificateDue = certificateDue;
	}

	public Short getEscorterState() {
		return this.escorterState;
	}

	public void setEscorterState(Short escorterState) {
		this.escorterState = escorterState;
	}

	public Set<TaskEscorter> getTaskEscorters() {
		return this.taskEscorters;
	}

	public void setTaskEscorters(Set<TaskEscorter> taskEscorters) {
		this.taskEscorters = taskEscorters;
	}

}
