package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FExpenseLog generated by hbm2java
 */
public class FExpenseLog implements java.io.Serializable {

	private long id;
	private Vehicle vehicle;
	private String category1;
	private String category2;
	private Short type;
	private Double amount;
	private String yearMonth;
	private String comment1;
	private String comment2;

	public FExpenseLog() {
	}

	public FExpenseLog(long id) {
		this.id = id;
	}

	public FExpenseLog(long id, Vehicle vehicle, String category1,
			String category2, Short type, Double amount, String yearMonth,
			String comment1, String comment2) {
		this.id = id;
		this.vehicle = vehicle;
		this.category1 = category1;
		this.category2 = category2;
		this.type = type;
		this.amount = amount;
		this.yearMonth = yearMonth;
		this.comment1 = comment1;
		this.comment2 = comment2;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public String getCategory1() {
		return this.category1;
	}

	public void setCategory1(String category1) {
		this.category1 = category1;
	}

	public String getCategory2() {
		return this.category2;
	}

	public void setCategory2(String category2) {
		this.category2 = category2;
	}

	public Short getType() {
		return this.type;
	}

	public void setType(Short type) {
		this.type = type;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public String getYearMonth() {
		return this.yearMonth;
	}

	public void setYearMonth(String yearMonth) {
		this.yearMonth = yearMonth;
	}

	public String getComment1() {
		return this.comment1;
	}

	public void setComment1(String comment1) {
		this.comment1 = comment1;
	}

	public String getComment2() {
		return this.comment2;
	}

	public void setComment2(String comment2) {
		this.comment2 = comment2;
	}

}
