package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.List;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.LockMode;
import static org.hibernate.criterion.Example.create;

/**
 * Home object for domain model class FExpenseLog.
 * @see com.gps.orm.FExpenseLog
 * @author Hibernate Tools
 */
public class FExpenseLogHome {

	private static final Log log = LogFactory.getLog(FExpenseLogHome.class);

	protected org.hibernate.Session getSession() {
		return HibernateUtil.getSession();
	}

	public void persist(FExpenseLog transientInstance) {
		log.debug("persisting FExpenseLog instance");
		try {
			getSession().persist(transientInstance);
			log.debug("persist successful");
		} catch (RuntimeException re) {
			log.error("persist failed", re);
			throw re;
		}
	}

	public void attachDirty(FExpenseLog instance) {
		log.debug("attaching dirty FExpenseLog instance");
		try {
			getSession().saveOrUpdate(instance);
			log.debug("attach successful");
		} catch (RuntimeException re) {
			log.error("attach failed", re);
			throw re;
		}
	}

	public void attachClean(FExpenseLog instance) {
		log.debug("attaching clean FExpenseLog instance");
		try {
			getSession().lock(instance, LockMode.NONE);
			log.debug("attach successful");
		} catch (RuntimeException re) {
			log.error("attach failed", re);
			throw re;
		}
	}

	public void delete(FExpenseLog persistentInstance) {
		log.debug("deleting FExpenseLog instance");
		try {
			getSession().delete(persistentInstance);
			log.debug("delete successful");
		} catch (RuntimeException re) {
			log.error("delete failed", re);
			throw re;
		}
	}

	public FExpenseLog merge(FExpenseLog detachedInstance) {
		log.debug("merging FExpenseLog instance");
		try {
			FExpenseLog result = (FExpenseLog) getSession().merge(
					detachedInstance);
			log.debug("merge successful");
			return result;
		} catch (RuntimeException re) {
			log.error("merge failed", re);
			throw re;
		}
	}

	public FExpenseLog findById(long id) {
		log.debug("getting FExpenseLog instance with id: " + id);
		try {
			FExpenseLog instance = (FExpenseLog) getSession().get(
					"com.gps.orm.FExpenseLog", id);
			if (instance == null) {
				log.debug("get successful, no instance found");
			} else {
				log.debug("get successful, instance found");
			}
			return instance;
		} catch (RuntimeException re) {
			log.error("get failed", re);
			throw re;
		}
	}

	public List<FExpenseLog> findByExample(FExpenseLog instance) {
		log.debug("finding FExpenseLog instance by example");
		try {
			List<FExpenseLog> results = (List<FExpenseLog>) getSession()
					.createCriteria("com.gps.orm.FExpenseLog").add(
							create(instance)).list();
			log.debug("find by example successful, result size: "
					+ results.size());
			return results;
		} catch (RuntimeException re) {
			log.error("find by example failed", re);
			throw re;
		}
	}
}
