package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * FMaterialKeepLogId generated by hbm2java
 */
public class FMaterialKeepLogId implements java.io.Serializable {

	private Long id;
	private Long materialId;
	private String keeper;
	private Date occurDate;
	private Integer operatorId;
	private String comment;

	public FMaterialKeepLogId() {
	}

	public FMaterialKeepLogId(Long id, Long materialId, String keeper,
			Date occurDate, Integer operatorId, String comment) {
		this.id = id;
		this.materialId = materialId;
		this.keeper = keeper;
		this.occurDate = occurDate;
		this.operatorId = operatorId;
		this.comment = comment;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getMaterialId() {
		return this.materialId;
	}

	public void setMaterialId(Long materialId) {
		this.materialId = materialId;
	}

	public String getKeeper() {
		return this.keeper;
	}

	public void setKeeper(String keeper) {
		this.keeper = keeper;
	}

	public Date getOccurDate() {
		return this.occurDate;
	}

	public void setOccurDate(Date occurDate) {
		this.occurDate = occurDate;
	}

	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FMaterialKeepLogId))
			return false;
		FMaterialKeepLogId castOther = (FMaterialKeepLogId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getMaterialId() == castOther.getMaterialId()) || (this
						.getMaterialId() != null
						&& castOther.getMaterialId() != null && this
						.getMaterialId().equals(castOther.getMaterialId())))
				&& ((this.getKeeper() == castOther.getKeeper()) || (this
						.getKeeper() != null
						&& castOther.getKeeper() != null && this.getKeeper()
						.equals(castOther.getKeeper())))
				&& ((this.getOccurDate() == castOther.getOccurDate()) || (this
						.getOccurDate() != null
						&& castOther.getOccurDate() != null && this
						.getOccurDate().equals(castOther.getOccurDate())))
				&& ((this.getOperatorId() == castOther.getOperatorId()) || (this
						.getOperatorId() != null
						&& castOther.getOperatorId() != null && this
						.getOperatorId().equals(castOther.getOperatorId())))
				&& ((this.getComment() == castOther.getComment()) || (this
						.getComment() != null
						&& castOther.getComment() != null && this.getComment()
						.equals(castOther.getComment())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getMaterialId() == null ? 0 : this.getMaterialId()
						.hashCode());
		result = 37 * result
				+ (getKeeper() == null ? 0 : this.getKeeper().hashCode());
		result = 37 * result
				+ (getOccurDate() == null ? 0 : this.getOccurDate().hashCode());
		result = 37
				* result
				+ (getOperatorId() == null ? 0 : this.getOperatorId()
						.hashCode());
		result = 37 * result
				+ (getComment() == null ? 0 : this.getComment().hashCode());
		return result;
	}

}
