package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * FMonthlyReport generated by hbm2java
 */
public class FMonthlyReport implements java.io.Serializable {

	private int id;
	private Vehicle vehicle;
	private String yearMonth;
	private Double income;
	private Double costs;
	private String note1;
	private String note2;
	private String note3;
	private String note4;
	private String note5;

	public FMonthlyReport() {
	}

	public FMonthlyReport(int id) {
		this.id = id;
	}

	public FMonthlyReport(int id, Vehicle vehicle, String yearMonth,
			Double income, Double costs, String note1, String note2,
			String note3, String note4, String note5) {
		this.id = id;
		this.vehicle = vehicle;
		this.yearMonth = yearMonth;
		this.income = income;
		this.costs = costs;
		this.note1 = note1;
		this.note2 = note2;
		this.note3 = note3;
		this.note4 = note4;
		this.note5 = note5;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public String getYearMonth() {
		return this.yearMonth;
	}

	public void setYearMonth(String yearMonth) {
		this.yearMonth = yearMonth;
	}

	public Double getIncome() {
		return this.income;
	}

	public void setIncome(Double income) {
		this.income = income;
	}

	public Double getCosts() {
		return this.costs;
	}

	public void setCosts(Double costs) {
		this.costs = costs;
	}

	public String getNote1() {
		return this.note1;
	}

	public void setNote1(String note1) {
		this.note1 = note1;
	}

	public String getNote2() {
		return this.note2;
	}

	public void setNote2(String note2) {
		this.note2 = note2;
	}

	public String getNote3() {
		return this.note3;
	}

	public void setNote3(String note3) {
		this.note3 = note3;
	}

	public String getNote4() {
		return this.note4;
	}

	public void setNote4(String note4) {
		this.note4 = note4;
	}

	public String getNote5() {
		return this.note5;
	}

	public void setNote5(String note5) {
		this.note5 = note5;
	}

}
