package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * FTyres generated by hbm2java
 */
public class FTyres implements java.io.Serializable {

	private long tyreId;
	private Vehicle vehicle;
	private String tyreNo;
	private String tyreName;
	private Short state;
	private String comment;
	private Date installDate;
	private Double installDistanceRec;
	private Double usedPeriod;
	private Date disposeDate;
	private Double disposeDistanceRec;
	private Double usedDistance;
	private Double price;
	private String operator;

	public FTyres() {
	}

	public FTyres(long tyreId) {
		this.tyreId = tyreId;
	}

	public FTyres(long tyreId, Vehicle vehicle, String tyreNo, String tyreName,
			Short state, String comment, Date installDate,
			Double installDistanceRec, Double usedPeriod, Date disposeDate,
			Double disposeDistanceRec, Double usedDistance, Double price,
			String operator) {
		this.tyreId = tyreId;
		this.vehicle = vehicle;
		this.tyreNo = tyreNo;
		this.tyreName = tyreName;
		this.state = state;
		this.comment = comment;
		this.installDate = installDate;
		this.installDistanceRec = installDistanceRec;
		this.usedPeriod = usedPeriod;
		this.disposeDate = disposeDate;
		this.disposeDistanceRec = disposeDistanceRec;
		this.usedDistance = usedDistance;
		this.price = price;
		this.operator = operator;
	}

	public long getTyreId() {
		return this.tyreId;
	}

	public void setTyreId(long tyreId) {
		this.tyreId = tyreId;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public String getTyreNo() {
		return this.tyreNo;
	}

	public void setTyreNo(String tyreNo) {
		this.tyreNo = tyreNo;
	}

	public String getTyreName() {
		return this.tyreName;
	}

	public void setTyreName(String tyreName) {
		this.tyreName = tyreName;
	}

	public Short getState() {
		return this.state;
	}

	public void setState(Short state) {
		this.state = state;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getInstallDate() {
		return this.installDate;
	}

	public void setInstallDate(Date installDate) {
		this.installDate = installDate;
	}

	public Double getInstallDistanceRec() {
		return this.installDistanceRec;
	}

	public void setInstallDistanceRec(Double installDistanceRec) {
		this.installDistanceRec = installDistanceRec;
	}

	public Double getUsedPeriod() {
		return this.usedPeriod;
	}

	public void setUsedPeriod(Double usedPeriod) {
		this.usedPeriod = usedPeriod;
	}

	public Date getDisposeDate() {
		return this.disposeDate;
	}

	public void setDisposeDate(Date disposeDate) {
		this.disposeDate = disposeDate;
	}

	public Double getDisposeDistanceRec() {
		return this.disposeDistanceRec;
	}

	public void setDisposeDistanceRec(Double disposeDistanceRec) {
		this.disposeDistanceRec = disposeDistanceRec;
	}

	public Double getUsedDistance() {
		return this.usedDistance;
	}

	public void setUsedDistance(Double usedDistance) {
		this.usedDistance = usedDistance;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

}
