package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.List;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.LockMode;
import static org.hibernate.criterion.Example.create;

/**
 * Home object for domain model class FUser.
 * @see com.gps.orm.FUser
 * @author Hibernate Tools
 */
public class FUserHome {

	private static final Log log = LogFactory.getLog(FUserHome.class);

	protected org.hibernate.Session getSession() {
		return HibernateUtil.getSession();
	}

	public void persist(FUser transientInstance) {
		log.debug("persisting FUser instance");
		try {
			getSession().persist(transientInstance);
			log.debug("persist successful");
		} catch (RuntimeException re) {
			log.error("persist failed", re);
			throw re;
		}
	}

	public void attachDirty(FUser instance) {
		log.debug("attaching dirty FUser instance");
		try {
			getSession().saveOrUpdate(instance);
			log.debug("attach successful");
		} catch (RuntimeException re) {
			log.error("attach failed", re);
			throw re;
		}
	}

	public void attachClean(FUser instance) {
		log.debug("attaching clean FUser instance");
		try {
			getSession().lock(instance, LockMode.NONE);
			log.debug("attach successful");
		} catch (RuntimeException re) {
			log.error("attach failed", re);
			throw re;
		}
	}

	public void delete(FUser persistentInstance) {
		log.debug("deleting FUser instance");
		try {
			getSession().delete(persistentInstance);
			log.debug("delete successful");
		} catch (RuntimeException re) {
			log.error("delete failed", re);
			throw re;
		}
	}

	public FUser merge(FUser detachedInstance) {
		log.debug("merging FUser instance");
		try {
			FUser result = (FUser) getSession().merge(detachedInstance);
			log.debug("merge successful");
			return result;
		} catch (RuntimeException re) {
			log.error("merge failed", re);
			throw re;
		}
	}

	public FUser findById(int id) {
		log.debug("getting FUser instance with id: " + id);
		try {
			FUser instance = (FUser) getSession().get("com.gps.orm.FUser", id);
			if (instance == null) {
				log.debug("get successful, no instance found");
			} else {
				log.debug("get successful, instance found");
			}
			return instance;
		} catch (RuntimeException re) {
			log.error("get failed", re);
			throw re;
		}
	}

	public List<FUser> findByExample(FUser instance) {
		log.debug("finding FUser instance by example");
		try {
			List<FUser> results = (List<FUser>) getSession().createCriteria(
					"com.gps.orm.FUser").add(create(instance)).list();
			log.debug("find by example successful, result size: "
					+ results.size());
			return results;
		} catch (RuntimeException re) {
			log.error("find by example failed", re);
			throw re;
		}
	}
}
