package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FVehicleMaterial generated by hbm2java
 */
public class FVehicleMaterial implements java.io.Serializable {

	private long materialId;
	private Vehicle vehicle;
	private String name;
	private String lastKeeper;
	private Date lastChangeDate;
	private Short state;
	private String comment;
	private Set<FMaterialKeepLog> FMaterialKeepLogs = new HashSet<FMaterialKeepLog>(
			0);

	public FVehicleMaterial() {
	}

	public FVehicleMaterial(long materialId) {
		this.materialId = materialId;
	}

	public FVehicleMaterial(long materialId, Vehicle vehicle, String name,
			String lastKeeper, Date lastChangeDate, Short state,
			String comment, Set<FMaterialKeepLog> FMaterialKeepLogs) {
		this.materialId = materialId;
		this.vehicle = vehicle;
		this.name = name;
		this.lastKeeper = lastKeeper;
		this.lastChangeDate = lastChangeDate;
		this.state = state;
		this.comment = comment;
		this.FMaterialKeepLogs = FMaterialKeepLogs;
	}

	public long getMaterialId() {
		return this.materialId;
	}

	public void setMaterialId(long materialId) {
		this.materialId = materialId;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastKeeper() {
		return this.lastKeeper;
	}

	public void setLastKeeper(String lastKeeper) {
		this.lastKeeper = lastKeeper;
	}

	public Date getLastChangeDate() {
		return this.lastChangeDate;
	}

	public void setLastChangeDate(Date lastChangeDate) {
		this.lastChangeDate = lastChangeDate;
	}

	public Short getState() {
		return this.state;
	}

	public void setState(Short state) {
		this.state = state;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Set<FMaterialKeepLog> getFMaterialKeepLogs() {
		return this.FMaterialKeepLogs;
	}

	public void setFMaterialKeepLogs(Set<FMaterialKeepLog> FMaterialKeepLogs) {
		this.FMaterialKeepLogs = FMaterialKeepLogs;
	}

}
