package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * GpsDeviceInstallation generated by hbm2java
 */
public class GpsDeviceInstallation implements java.io.Serializable {

	private int id;
	private Integer vehicleId;
	private Short installState;
	private Date installDate;
	private String deviceId;
	private String deviceType;
	private String commPotocol;
	private Double costs;

	public GpsDeviceInstallation() {
	}

	public GpsDeviceInstallation(int id) {
		this.id = id;
	}

	public GpsDeviceInstallation(int id, Integer vehicleId, Short installState,
			Date installDate, String deviceId, String deviceType,
			String commPotocol, Double costs) {
		this.id = id;
		this.vehicleId = vehicleId;
		this.installState = installState;
		this.installDate = installDate;
		this.deviceId = deviceId;
		this.deviceType = deviceType;
		this.commPotocol = commPotocol;
		this.costs = costs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	public Short getInstallState() {
		return this.installState;
	}

	public void setInstallState(Short installState) {
		this.installState = installState;
	}

	public Date getInstallDate() {
		return this.installDate;
	}

	public void setInstallDate(Date installDate) {
		this.installDate = installDate;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public String getCommPotocol() {
		return this.commPotocol;
	}

	public void setCommPotocol(String commPotocol) {
		this.commPotocol = commPotocol;
	}

	public Double getCosts() {
		return this.costs;
	}

	public void setCosts(Double costs) {
		this.costs = costs;
	}

}
