package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Gpsfee generated by hbm2java
 */
public class Gpsfee implements java.io.Serializable {

	private long feeId;
	private Users users;
	private Vehicle vehicle;
	private Date receiveDate;
	private Short feeType;
	private Date dueDate;
	private String memo;
	private Double money;

	public Gpsfee() {
	}

	public Gpsfee(long feeId) {
		this.feeId = feeId;
	}

	public Gpsfee(long feeId, Users users, Vehicle vehicle, Date receiveDate,
			Short feeType, Date dueDate, String memo, Double money) {
		this.feeId = feeId;
		this.users = users;
		this.vehicle = vehicle;
		this.receiveDate = receiveDate;
		this.feeType = feeType;
		this.dueDate = dueDate;
		this.memo = memo;
		this.money = money;
	}

	public long getFeeId() {
		return this.feeId;
	}

	public void setFeeId(long feeId) {
		this.feeId = feeId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Date getReceiveDate() {
		return this.receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public Short getFeeType() {
		return this.feeType;
	}

	public void setFeeType(Short feeType) {
		this.feeType = feeType;
	}

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

}
