package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PictureStore generated by hbm2java
 */
public class PictureStore implements java.io.Serializable {

	private int storageId;
	private byte[] picData;
	private String comment;
	private Date lastModifyDate;
	private Integer lastModifyBy;
	private Set<VehiclePic> vehiclePics = new HashSet<VehiclePic>(0);

	public PictureStore() {
	}

	public PictureStore(int storageId) {
		this.storageId = storageId;
	}

	public PictureStore(int storageId, byte[] picData, String comment,
			Date lastModifyDate, Integer lastModifyBy,
			Set<VehiclePic> vehiclePics) {
		this.storageId = storageId;
		this.picData = picData;
		this.comment = comment;
		this.lastModifyDate = lastModifyDate;
		this.lastModifyBy = lastModifyBy;
		this.vehiclePics = vehiclePics;
	}

	public int getStorageId() {
		return this.storageId;
	}

	public void setStorageId(int storageId) {
		this.storageId = storageId;
	}

	public byte[] getPicData() {
		return this.picData;
	}

	public void setPicData(byte[] picData) {
		this.picData = picData;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getLastModifyDate() {
		return this.lastModifyDate;
	}

	public void setLastModifyDate(Date lastModifyDate) {
		this.lastModifyDate = lastModifyDate;
	}

	public Integer getLastModifyBy() {
		return this.lastModifyBy;
	}

	public void setLastModifyBy(Integer lastModifyBy) {
		this.lastModifyBy = lastModifyBy;
	}

	public Set<VehiclePic> getVehiclePics() {
		return this.vehiclePics;
	}

	public void setVehiclePics(Set<VehiclePic> vehiclePics) {
		this.vehiclePics = vehiclePics;
	}

}
