package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

/**
 * QualifiedCoordArea generated by hbm2java
 */
public class QualifiedCoordArea implements java.io.Serializable {

	private int id;
	private Double northEastLong;
	private Double northEastLat;
	private Double southWestLong;
	private Double southWestLat;

	public QualifiedCoordArea() {
	}

	public QualifiedCoordArea(int id) {
		this.id = id;
	}

	public QualifiedCoordArea(int id, Double northEastLong,
			Double northEastLat, Double southWestLong, Double southWestLat) {
		this.id = id;
		this.northEastLong = northEastLong;
		this.northEastLat = northEastLat;
		this.southWestLong = southWestLong;
		this.southWestLat = southWestLat;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Double getNorthEastLong() {
		return this.northEastLong;
	}

	public void setNorthEastLong(Double northEastLong) {
		this.northEastLong = northEastLong;
	}

	public Double getNorthEastLat() {
		return this.northEastLat;
	}

	public void setNorthEastLat(Double northEastLat) {
		this.northEastLat = northEastLat;
	}

	public Double getSouthWestLong() {
		return this.southWestLong;
	}

	public void setSouthWestLong(Double southWestLong) {
		this.southWestLong = southWestLong;
	}

	public Double getSouthWestLat() {
		return this.southWestLat;
	}

	public void setSouthWestLat(Double southWestLat) {
		this.southWestLat = southWestLat;
	}

}
