package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

/**
 * RegionPoints generated by hbm2java
 */
public class RegionPoints implements java.io.Serializable {

	private int pointId;
	private Region region;
	private Double longVal;
	private Double latVal;

	public RegionPoints() {
	}

	public RegionPoints(int pointId) {
		this.pointId = pointId;
	}

	public RegionPoints(int pointId, Region region, Double longVal,
			Double latVal) {
		this.pointId = pointId;
		this.region = region;
		this.longVal = longVal;
		this.latVal = latVal;
	}

	public int getPointId() {
		return this.pointId;
	}

	public void setPointId(int pointId) {
		this.pointId = pointId;
	}

	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	public Double getLongVal() {
		return this.longVal;
	}

	public void setLongVal(Double longVal) {
		this.longVal = longVal;
	}

	public Double getLatVal() {
		return this.latVal;
	}

	public void setLatVal(Double latVal) {
		this.latVal = latVal;
	}

}
