package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	private int regionId;
	private RegionTypeDic regionTypeDic;
	private String name;
	private String description;
	private Double centralLong;
	private Double centralLat;
	private Double radius;
	private Double edgeLong;
	private Double edgeLat;
	private Short figurType;
	private Set<RegionPoints> regionPointses = new HashSet<RegionPoints>(0);

	public Region() {
	}

	public Region(int regionId) {
		this.regionId = regionId;
	}

	public Region(int regionId, RegionTypeDic regionTypeDic, String name,
			String description, Double centralLong, Double centralLat,
			Double radius, Double edgeLong, Double edgeLat, Short figurType,
			Set<RegionPoints> regionPointses) {
		this.regionId = regionId;
		this.regionTypeDic = regionTypeDic;
		this.name = name;
		this.description = description;
		this.centralLong = centralLong;
		this.centralLat = centralLat;
		this.radius = radius;
		this.edgeLong = edgeLong;
		this.edgeLat = edgeLat;
		this.figurType = figurType;
		this.regionPointses = regionPointses;
	}

	public int getRegionId() {
		return this.regionId;
	}

	public void setRegionId(int regionId) {
		this.regionId = regionId;
	}

	public RegionTypeDic getRegionTypeDic() {
		return this.regionTypeDic;
	}

	public void setRegionTypeDic(RegionTypeDic regionTypeDic) {
		this.regionTypeDic = regionTypeDic;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getCentralLong() {
		return this.centralLong;
	}

	public void setCentralLong(Double centralLong) {
		this.centralLong = centralLong;
	}

	public Double getCentralLat() {
		return this.centralLat;
	}

	public void setCentralLat(Double centralLat) {
		this.centralLat = centralLat;
	}

	public Double getRadius() {
		return this.radius;
	}

	public void setRadius(Double radius) {
		this.radius = radius;
	}

	public Double getEdgeLong() {
		return this.edgeLong;
	}

	public void setEdgeLong(Double edgeLong) {
		this.edgeLong = edgeLong;
	}

	public Double getEdgeLat() {
		return this.edgeLat;
	}

	public void setEdgeLat(Double edgeLat) {
		this.edgeLat = edgeLat;
	}

	public Short getFigurType() {
		return this.figurType;
	}

	public void setFigurType(Short figurType) {
		this.figurType = figurType;
	}


	public Set<RegionPoints> getRegionPointses() {
		return this.regionPointses;
	}

	public void setRegionPointses(Set<RegionPoints> regionPointses) {
		this.regionPointses = regionPointses;
	}

}
