package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rules generated by hbm2java
 */
public class Rules implements java.io.Serializable {

	private int ruleId;
	private AlertTypeDic alertTypeDic;
	private String ruleName;
	private Integer intParam1;
	private Date timeParam;
	private short opType;
	private short ruleType;
	private short ruleState;
	private Set<SegmentRules> segmentRuleses = new HashSet<SegmentRules>(0);
	private Set<VehicleRule> vehicleRules = new HashSet<VehicleRule>(0);
	private Set<TaskRule> taskRules = new HashSet<TaskRule>(0);

	public Rules() {
	}

	public Rules(int ruleId, short opType, short ruleType, short ruleState) {
		this.ruleId = ruleId;
		this.opType = opType;
		this.ruleType = ruleType;
		this.ruleState = ruleState;
	}

	public Rules(int ruleId, AlertTypeDic alertTypeDic, String ruleName,
			Integer intParam1, Date timeParam, short opType, short ruleType,
			short ruleState, Set<SegmentRules> segmentRuleses,
			Set<VehicleRule> vehicleRules, Set<TaskRule> taskRules) {
		this.ruleId = ruleId;
		this.alertTypeDic = alertTypeDic;
		this.ruleName = ruleName;
		this.intParam1 = intParam1;
		this.timeParam = timeParam;
		this.opType = opType;
		this.ruleType = ruleType;
		this.ruleState = ruleState;
		this.segmentRuleses = segmentRuleses;
		this.vehicleRules = vehicleRules;
		this.taskRules = taskRules;
	}

	public int getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(int ruleId) {
		this.ruleId = ruleId;
	}

	public AlertTypeDic getAlertTypeDic() {
		return this.alertTypeDic;
	}

	public void setAlertTypeDic(AlertTypeDic alertTypeDic) {
		this.alertTypeDic = alertTypeDic;
	}

	public String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}

	public Integer getIntParam1() {
		return this.intParam1;
	}

	public void setIntParam1(Integer intParam1) {
		this.intParam1 = intParam1;
	}

	public Date getTimeParam() {
		return this.timeParam;
	}

	public void setTimeParam(Date timeParam) {
		this.timeParam = timeParam;
	}

	public short getOpType() {
		return this.opType;
	}

	public void setOpType(short opType) {
		this.opType = opType;
	}

	public short getRuleType() {
		return this.ruleType;
	}

	public void setRuleType(short ruleType) {
		this.ruleType = ruleType;
	}

	public short getRuleState() {
		return this.ruleState;
	}

	public void setRuleState(short ruleState) {
		this.ruleState = ruleState;
	}

	public Set<SegmentRules> getSegmentRuleses() {
		return this.segmentRuleses;
	}

	public void setSegmentRuleses(Set<SegmentRules> segmentRuleses) {
		this.segmentRuleses = segmentRuleses;
	}

	public Set<VehicleRule> getVehicleRules() {
		return this.vehicleRules;
	}

	public void setVehicleRules(Set<VehicleRule> vehicleRules) {
		this.vehicleRules = vehicleRules;
	}

	public Set<TaskRule> getTaskRules() {
		return this.taskRules;
	}

	public void setTaskRules(Set<TaskRule> taskRules) {
		this.taskRules = taskRules;
	}

}
