package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * StateHelper generated by hbm2java
 */
public class StateHelper implements java.io.Serializable {

	private int vehicleId;
	private Vehicle vehicle;
	private Date lastMessage;
	private Date lastUpdate;
	private Byte lastUpdateType;
	private Date lastStopTime;
	private Date startRuningTime;

	public StateHelper() {
	}

	public StateHelper(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public StateHelper(Vehicle vehicle, Date lastMessage, Date lastUpdate,
			Byte lastUpdateType, Date lastStopTime, Date startRuningTime) {
		this.vehicle = vehicle;
		this.lastMessage = lastMessage;
		this.lastUpdate = lastUpdate;
		this.lastUpdateType = lastUpdateType;
		this.lastStopTime = lastStopTime;
		this.startRuningTime = startRuningTime;
	}

	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Date getLastMessage() {
		return this.lastMessage;
	}

	public void setLastMessage(Date lastMessage) {
		this.lastMessage = lastMessage;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	public Byte getLastUpdateType() {
		return this.lastUpdateType;
	}

	public void setLastUpdateType(Byte lastUpdateType) {
		this.lastUpdateType = lastUpdateType;
	}

	public Date getLastStopTime() {
		return this.lastStopTime;
	}

	public void setLastStopTime(Date lastStopTime) {
		this.lastStopTime = lastStopTime;
	}

	public Date getStartRuningTime() {
		return this.startRuningTime;
	}

	public void setStartRuningTime(Date startRuningTime) {
		this.startRuningTime = startRuningTime;
	}

}
