package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.List;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.LockMode;
import static org.hibernate.criterion.Example.create;

/**
 * Home object for domain model class TzUsers.
 * @see com.gps.orm.TzUsers
 * @author Hibernate Tools
 */
public class TzUsersHome {

	private static final Log log = LogFactory.getLog(TzUsersHome.class);

	protected org.hibernate.Session getSession() {
		return HibernateUtil.getSession();
	}

	public void persist(TzUsers transientInstance) {
		log.debug("persisting TzUsers instance");
		try {
			getSession().persist(transientInstance);
			log.debug("persist successful");
		} catch (RuntimeException re) {
			log.error("persist failed", re);
			throw re;
		}
	}

	public void attachDirty(TzUsers instance) {
		log.debug("attaching dirty TzUsers instance");
		try {
			getSession().saveOrUpdate(instance);
			log.debug("attach successful");
		} catch (RuntimeException re) {
			log.error("attach failed", re);
			throw re;
		}
	}

	public void attachClean(TzUsers instance) {
		log.debug("attaching clean TzUsers instance");
		try {
			getSession().lock(instance, LockMode.NONE);
			log.debug("attach successful");
		} catch (RuntimeException re) {
			log.error("attach failed", re);
			throw re;
		}
	}

	public void delete(TzUsers persistentInstance) {
		log.debug("deleting TzUsers instance");
		try {
			getSession().delete(persistentInstance);
			log.debug("delete successful");
		} catch (RuntimeException re) {
			log.error("delete failed", re);
			throw re;
		}
	}

	public TzUsers merge(TzUsers detachedInstance) {
		log.debug("merging TzUsers instance");
		try {
			TzUsers result = (TzUsers) getSession().merge(detachedInstance);
			log.debug("merge successful");
			return result;
		} catch (RuntimeException re) {
			log.error("merge failed", re);
			throw re;
		}
	}

	public TzUsers findById(int id) {
		log.debug("getting TzUsers instance with id: " + id);
		try {
			TzUsers instance = (TzUsers) getSession().get(
					"com.gps.orm.TzUsers", id);
			if (instance == null) {
				log.debug("get successful, no instance found");
			} else {
				log.debug("get successful, instance found");
			}
			return instance;
		} catch (RuntimeException re) {
			log.error("get failed", re);
			throw re;
		}
	}

	public List<TzUsers> findByExample(TzUsers instance) {
		log.debug("finding TzUsers instance by example");
		try {
			List<TzUsers> results = (List<TzUsers>) getSession()
					.createCriteria("com.gps.orm.TzUsers")
					.add(create(instance)).list();
			log.debug("find by example successful, result size: "
					+ results.size());
			return results;
		} catch (RuntimeException re) {
			log.error("find by example failed", re);
			throw re;
		}
	}
}
