package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

/**
 * VehicleAssociations generated by hbm2java
 */
public class VehicleAssociations implements java.io.Serializable {

	private int assoId;
	private Vehicle vehicle;
	private Short roleType;
	private Integer targetId;

	public VehicleAssociations() {
	}

	public VehicleAssociations(int assoId) {
		this.assoId = assoId;
	}

	public VehicleAssociations(int assoId, Vehicle vehicle, Short roleType,
			Integer targetId) {
		this.assoId = assoId;
		this.vehicle = vehicle;
		this.roleType = roleType;
		this.targetId = targetId;
	}

	public int getAssoId() {
		return this.assoId;
	}

	public void setAssoId(int assoId) {
		this.assoId = assoId;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Short getRoleType() {
		return this.roleType;
	}

	public void setRoleType(Short roleType) {
		this.roleType = roleType;
	}

	public Integer getTargetId() {
		return this.targetId;
	}

	public void setTargetId(Integer targetId) {
		this.targetId = targetId;
	}

}
