package com.gps.orm;

// Generated 2010-2-25 23:09:46 by Hibernate Tools 3.2.4.GA

/**
 * VehicleRule generated by hbm2java
 */
public class VehicleRule implements java.io.Serializable {

	private int id;
	private Vehicle vehicle;
	private Rules rules;
	private Short tag;

	public VehicleRule() {
	}

	public VehicleRule(int id) {
		this.id = id;
	}

	public VehicleRule(int id, Vehicle vehicle, Rules rules, Short tag) {
		this.id = id;
		this.vehicle = vehicle;
		this.rules = rules;
		this.tag = tag;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Rules getRules() {
		return this.rules;
	}

	public void setRules(Rules rules) {
		this.rules = rules;
	}

	public Short getTag() {
		return this.tag;
	}

	public void setTag(Short tag) {
		this.tag = tag;
	}

}
