package com.gps.orm;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * VehiclePicTypeDic generated by hbm2java
 */
public class VehiclePicTypeDic implements java.io.Serializable {

	private int vehiclePicTypeId;
	private String vehiclePicTypeName;
	private String description;
	private Short stateTag;
	private Set<VehiclePic> vehiclePics = new HashSet<VehiclePic>(0);

	public VehiclePicTypeDic() {
	}

	public VehiclePicTypeDic(int vehiclePicTypeId) {
		this.vehiclePicTypeId = vehiclePicTypeId;
	}

	public VehiclePicTypeDic(int vehiclePicTypeId, String vehiclePicTypeName,
			String description, Short stateTag, Set<VehiclePic> vehiclePics) {
		this.vehiclePicTypeId = vehiclePicTypeId;
		this.vehiclePicTypeName = vehiclePicTypeName;
		this.description = description;
		this.stateTag = stateTag;
		this.vehiclePics = vehiclePics;
	}

	public int getVehiclePicTypeId() {
		return this.vehiclePicTypeId;
	}

	public void setVehiclePicTypeId(int vehiclePicTypeId) {
		this.vehiclePicTypeId = vehiclePicTypeId;
	}

	public String getVehiclePicTypeName() {
		return this.vehiclePicTypeName;
	}

	public void setVehiclePicTypeName(String vehiclePicTypeName) {
		this.vehiclePicTypeName = vehiclePicTypeName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Short getStateTag() {
		return this.stateTag;
	}

	public void setStateTag(Short stateTag) {
		this.stateTag = stateTag;
	}

	public Set<VehiclePic> getVehiclePics() {
		return this.vehiclePics;
	}

	public void setVehiclePics(Set<VehiclePic> vehiclePics) {
		this.vehiclePics = vehiclePics;
	}

}
